"""create order_status_history table

Revision ID: 087770ba3661
Revises: ffed1260630a
Create Date: 2026-09-17 13:41:14.886953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087770ba3661'
down_revision: Union[str, Sequence[str], None] = 'ffed1260630a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'PAID', 'FULFILLED', 'CANCELLED', 'REFUNDED', name='order_status', native_enum=False, length=20), nullable=False),
    sa.Column('to_status', sa.Enum('PENDING', 'PAID', 'FULFILLED', 'CANCELLED', 'REFUNDED', name='order_status', native_enum=False, length=20), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
