"""composite unique orders tables

Revision ID: 34572bfe5aab
Revises: fef4e309ba77
Create Date: 2026-09-28 13:05:30.542661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34572bfe5aab'
down_revision: Union[str, Sequence[str], None] = 'fef4e309ba77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=False)
    op.create_unique_constraint('uq_orders_user_id_idempotency_key', 'orders', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_user_id_idempotency_key', 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###
