"""create order, order_item and order_status_history tables

Revision ID: 70f3d690fec2
Revises: 2b6afee7cf56
Create Date: 2026-09-15 13:41:30.197828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f3d690fec2'
down_revision: Union[str, Sequence[str], None] = '2b6afee7cf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
