"""update cart tables

Revision ID: 76295f2692bc
Revises: 34572bfe5aab
Create Date: 2026-09-29 10:18:03.741063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76295f2692bc'
down_revision: Union[str, Sequence[str], None] = '34572bfe5aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('guest_token', sa.String(length=64), nullable=True))
    op.alter_column('carts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_carts_guest_token'), 'carts', ['guest_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carts_guest_token'), table_name='carts')
    op.alter_column('carts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('carts', 'guest_token')
    # ### end Alembic commands ###
