"""update refresh_tokens tables

Revision ID: 9446956fb47e
Revises: cbbf5e6d9b56
Create Date: 2026-10-01 10:33:50.261204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9446956fb47e'
down_revision: Union[str, Sequence[str], None] = 'cbbf5e6d9b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_token', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_recipient_name', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('shipping_line1', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_line2', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=2), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_orders_guest_token'), 'orders', ['guest_token'], unique=False)
    op.create_unique_constraint('uq_orders_guest_token_idempotency_key', 'orders', ['guest_token', 'idempotency_key'])
    op.add_column('refresh_tokens', sa.Column('family_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'family_id')
    op.drop_constraint('uq_orders_guest_token_idempotency_key', 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_guest_token'), table_name='orders')
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_line2')
    op.drop_column('orders', 'shipping_line1')
    op.drop_column('orders', 'shipping_recipient_name')
    op.drop_column('orders', 'guest_email')
    op.drop_column('orders', 'guest_token')
    # ### end Alembic commands ###
