"""update payment tables

Revision ID: fef4e309ba77
Revises: c0cc58801d7a
Create Date: 2026-09-28 12:30:05.268851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef4e309ba77'
down_revision: Union[str, Sequence[str], None] = 'c0cc58801d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_refund_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('refunded_amount_cents', sa.Integer(), nullable=True))
    op.drop_index(op.f('ux_payments_order_id_pending'), table_name='payments', postgresql_where="(status = 'pending'::payment_status)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_payments_order_id_pending'), 'payments', ['order_id'], unique=True, postgresql_where="(status = 'pending'::payment_status)")
    op.drop_column('payments', 'refunded_amount_cents')
    op.drop_column('payments', 'provider_refund_id')
    # ### end Alembic commands ###
